server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aleksandar-pejkovic/fitness-config-repo

  security:
    user:
      name: root
      password: s3cr3t
